### ISSUE TITLE
弄了几天，老是错误，请帮忙看看

### ISSUE THREAD

**Issue by aobenny** [SpringCity-LaoYang/AutoXue-multiuser#34]
D:\pro\AutoXue
Appium.exe                   16736 Console                    1     94,100 K
Appium.exe                    5744 Console                    1     33,116 K
Appium.exe                   25240 Console                    1      5,992 K
Appium.exe                   29224 Console                    1     78,628 K
Appium is running
Nox.exe                      25368 Console                    1     28,568 K
Nox is running
[INFO] 正在连接模拟器 127.0.0.1:62001，请稍候...
Traceback (most recent call last):
  File "D:\pro\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\pro\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\pro\AutoXue\xuexi\__main__.py", line 17, in <module>
    app = App()
  File "D:\pro\AutoXue\xuexi\__init__.py", line 118, in __init__
    super().__init__()
  File "D:\pro\AutoXue\xuexi\__init__.py", line 29, in __init__
    self.connect()
  File "D:\pro\AutoXue\xuexi\__init__.py", line 50, in connect
    if 0 == subprocess.check_call(f'adb connect {caps["uuid"]}', shell=True, stdout=subprocess.PIPE):
  File "D:\pro\python38\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'adb connect 127.0.0.1:62001' returned non-zero exit status 1.
Exception ignored in: <function Automation.__del__ at 0x04097B20>
Traceback (most recent call last):
  File "D:\pro\AutoXue\xuexi\__init__.py", line 105, in __del__
    self.driver.close_app()
AttributeError: 'App' object has no attribute 'driver'
xuexi successfully!
请按任意键继续. . .

**Comment by zz803abc** [comment]
adb的原因，建议再重新配置环境。

**Comment by aobenny** [comment]
谢谢终于搞定这个问题了

**Comment by fightergg2** [comment]
我也是同样的问题，请问您是如何解决的？可以传授一下吗？

**Comment by aobenny** [comment]
> 我也是同样的问题，请问您是如何解决的？可以传授一下吗？

我在系统的环境变量的path里，直接添加了夜神模拟器的adb绝对目录，并且置于第一位调用。
