### ISSUE TITLE
这是什么问题

### ISSUE THREAD

**Issue by fuckxszy** [SpringCity-LaoYang/AutoXue-multiuser#9]
D:\AutoXue-multiuser-master
Appium.exe                   11944 Console                    1    144,888 K
Appium.exe                    9404 Console                    1     56,336 K
Appium.exe                   10224 Console                    1    124,280 K
Appium.exe                    9932 Console                    1     28,872 K
Nox.exe                      12000 Console                    1     31,280 K
Traceback (most recent call last):
  File "C:\Users\andon\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 184, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\andon\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 143, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\andon\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "D:\AutoXue-multiuser-master\xuexi\__init__.py", line 13, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
请按任意键继续. . .

**Comment by SpringCity-LaoYang** [comment]
自己执行“pip install request”
